<?php

namespace CoreBundle\Repository;

/**
 * ProjetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetRepository extends \Doctrine\ORM\EntityRepository
{
    public function getProjetsByUser($user){
        $qb = $this->createQueryBuilder('p');
        $qb->select('p')
            ->leftJoin('p.user', 'c')
            ->where('c.id = ?1')
            ->setParameter(1, $user);

        return $qb->getQuery()->getResult();
    }
}
